version: "3"
services:

  client_web:
    build: ./area_front_web
    networks:
      - api-tier
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - server
      - client_mobile
    volumes:
      - shared_volume:/usr/src/app-release/
      - ./area_front_web:/usr/src/app
    environment:
      BASE_URL: ${APP_URL}
      CLIENT_ID: ${GITHUB_CLIENT_ID}
      SCOPE: ${SCOPE}
      MSTEAMS_CLIENT_ID: ${MSTEAMS_CLIENT_ID}
      MSTEAMS_CLIENT_SECRET: ${MSTEAMS_CLIENT_SECRET}
      MSTEAMS_CLIENT_SCOPE: ${MSTEAMS_CLIENT_SCOPE}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_CLIENT_SCOPE: ${SPOTIFY_CLIENT_SCOPE}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_CLIENT_SCOPE: ${DISCORD_CLIENT_SCOPE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_SCOPE: ${GOOGLE_CLIENT_SCOPE}

  server:
    build: ./api
    networks:
      - api-tier
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - shared_volume:/usr/src/app-release/
      - ./api:/usr/src/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      MODE: ${MODE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      APP_URL: ${APP_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      MSTEAMS_CLIENT_ID: ${MSTEAMS_CLIENT_ID}
      MSTEAMS_CLIENT_SECRET: ${MSTEAMS_CLIENT_SECRET}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      METEO_API_KEY: ${METEO_API_KEY}
      FIVE_MINUTES_ACTIONS: ${FIVE_MINUTES_ACTIONS}
      ONE_DAY_ACTIONS: ${ONE_DAY_ACTIONS}
      MJ_APIKEY_PUBLIC: ${MJ_APIKEY_PUBLIC}
      MJ_APIKEY_PRIVATE: ${MJ_APIKEY_PRIVATE}

  client_mobile:
    build:
      context: ./area_front_app
      dockerfile: Dockerfile
    volumes:
      - shared_volume:/usr/src/app-release/
    environment:
      BASE_URL: ${APP_URL}
      CLIENT_ID: ${GITHUB_CLIENT_ID}
      SCOPE: ${SCOPE}
      MSTEAMS_CLIENT_ID: ${MSTEAMS_CLIENT_ID}
      MSTEAMS_CLIENT_SECRET: ${MSTEAMS_CLIENT_SECRET}
      MSTEAMS_CLIENT_SCOPE: ${MSTEAMS_CLIENT_SCOPE}'
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_CLIENT_SCOPE: ${SPOTIFY_CLIENT_SCOPE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SCOPE: ${GOOGLE_CLIENT_SCOPE}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_CLIENT_SCOPE: ${DISCORD_CLIENT_SCOPE}

volumes:
  shared_volume:

networks:
  api-tier:
