name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
