name: AREA CI-CD

on:
  pull_request:
    branches: [main]

jobs:
  run_flutter_compile:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Run Flutter tests
    steps:
      - uses: actions/checkout@v3
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
      - name: Install dependencies
        working-directory: ./area_front_app
        run: |
          flutter pub get
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
      - name: Check Syntax
        run: flutter analyze
      - name: Run tests
        working-directory: ./area_front_app
        run: flutter test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}  

  run_nestJS_test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Run NestJS tests
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./api
        run: npm rm -rf node_modules package-lock.json && npm install
      - name: Run tests
        working-directory: ./api
        run: npm run test
    continue-on-error: false

  run_reactJS_test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Run ReactJS tests
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./area_front_web
        run: npm rm -rf node_modules package-lock.json && npm install
      - name: Run tests
        working-directory: ./area_front_web
        run: npm run test
    continue-on-error: false
