name: "Build APK for Release"

on:
  push:
    branches:
        - main

env:
  APK_OUTPUT: area_front_app/build/app/outputs/apk/release/

jobs:
  release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env File
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" > area_front_app/.env
      - name: Flutter Install
        uses: subosito/flutter-action@v2.10.0
        with:
          channel: 'stable'
          architecture: x64
          cache: true
      - name: Flutter Android Build
        working-directory: area_front_app
        run: |
          flutter pub get
          flutter analyze
          flutter build apk --release --no-tree-shake-icons

      - name: Rename APK
        run: |
          mv ${{ env.APK_OUTPUT }}app-release.apk ${{ env.APK_OUTPUT }}area.apk

      - name: Create GitHub Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
            repo_token: ${{ secrets.AREA_TOKEN }}
            prerelease: false
            files: ${{ env.APK_OUTPUT }}area.apk
            automatic_release_tag: "latest"